// tableStates.js
export const TABLE_STATUS = {
    FREE: 'FREE',
    OCCUPIED: 'OCCUPIED',
    RESERVED: 'RESERVED',
    // DIRTY: 'DIRTY', // Future proofing
};

// The "Smart" Map
export const ALLOWED_TABLE_TRANSITIONS = {
    [TABLE_STATUS.FREE]: [TABLE_STATUS.OCCUPIED, TABLE_STATUS.RESERVED],
    [TABLE_STATUS.RESERVED]: [TABLE_STATUS.OCCUPIED, TABLE_STATUS.FREE],
    [TABLE_STATUS.OCCUPIED]: [TABLE_STATUS.FREE],
    // If you add DIRTY later: OCCUPIED -> DIRTY -> FREE
};