import { ORDER_STATUS } from "./orderStates.js";

export const ALLOWED_TRANSITIONS = {
    [ORDER_STATUS.PLACED]: [ORDER_STATUS.PREPARING],
    [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY],
    [ORDER_STATUS.READY]: [ORDER_STATUS.SERVED],
    [ORDER_STATUS.SERVED]: [],
};
