import { ORDER_ITEM_STATUS } from "./orderItemStates.js";

export const ALLOWED_ITEM_TRANSITIONS = {
    [ORDER_ITEM_STATUS.PENDING]: [ORDER_ITEM_STATUS.PREPARING, ORDER_ITEM_STATUS.CANCELLED],
    [ORDER_ITEM_STATUS.PREPARING]: [ORDER_ITEM_STATUS.READY, ORDER_ITEM_STATUS.CANCELLED],
    [ORDER_ITEM_STATUS.READY]: [ORDER_ITEM_STATUS.SERVED, ORDER_ITEM_STATUS.CANCELLED], // Can cancel if dropped on floor
    [ORDER_ITEM_STATUS.SERVED]: [], // Final state
    [ORDER_ITEM_STATUS.CANCELLED]: []  // Final state
};