import { ORDER_STATUS } from "./orderStates.js";

export const ALLOWED_TRANSITIONS = {
    [ORDER_STATUS.PLACED]: [ORDER_STATUS.PREPARING, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY, ORDER_STATUS.CANCELLED], // Manager might cancel if out of stock
    [ORDER_STATUS.READY]: [ORDER_STATUS.SERVED, ORDER_STATUS.CANCELLED], // Customer left before eating
    [ORDER_STATUS.SERVED]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELLED], // Manager void (complain)
    [ORDER_STATUS.COMPLETED]: [], // Final State
    [ORDER_STATUS.CANCELLED]: []  // Final State
};